name: Build

on: [push]

jobs:
  
  build:
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.10", "3.11"]

    runs-on: ${{ matrix.os }}

    steps:
    
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update System
        if: runner.os == 'Linux'
        run: |          
          sudo apt-get install -y libzbar0 libmtdev1 libmtdev-dev
          sudo ldconfig -v
          
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade Cython
          pip install poetry
          poetry install

      # Build needs some display
      # Running without a headless display
      # into github-action worker
      # will cause a "Couldn't connect to X Server"
      # To fix that, setup a headless window server
      - name: Build executables
        uses: coactions/setup-xvfb@v1
        with:
          run: poetry run poe build

      - name: Upload ksigner-cli artifact
        uses: actions/upload-artifact@v3
        with:
          name: ksigner-${{ runner.os }}-py${{ matrix.python-version }}
          path: ./dist/ksigner-*
