name: Pylint

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
  
    - name: Install dependencies
      run: |
        sudo apt-get install -y libzbar0
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
        
    - name: Build ksigner-cli and ksigner-gui
      run: poetry run poe build

    - name: Upload ksigner-cli artifact
      uses: actions/upload-artifact@v3
      with:
        name: ksigner-linux
        path: |
          ./dist/ksigner-cli-linux
          ./dist/ksigner-gui-linux
